// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleDetail: typeof import('./components/Article/ArticleDetail.vue')['default']
    ArticleList: typeof import('./components/Article/ArticleList.vue')['default']
    Banner: typeof import('./components/home/Banner.vue')['default']
    Calendar: typeof import('./components/Calendar/index.vue')['default']
    Captcha: typeof import('./components/Captcha.vue')['default']
    DeckDetailComponent: typeof import('./components/Deck/DeckDetailComponent.vue')['default']
    DeckWin: typeof import('./components/Deck/DeckWin.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./components/common/Footer.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    LoginPop: typeof import('./components/common/LoginPop.vue')['default']
    Navbar: typeof import('./components/common/Navbar.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PriceChart: typeof import('./components/Cards/PriceChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCards: typeof import('./components/Cards/SearchCards.vue')['default']
    Sideboard: typeof import('./components/common/Sideboard.vue')['default']
    TopArticle: typeof import('./components/home/TopArticle.vue')['default']
  }
}
