// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleList: typeof import('./components/Article/ArticleList.vue')['default']
    Banner: typeof import('./components/home/Banner.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./components/common/Footer.vue')['default']
    Navbar: typeof import('./components/common/Navbar.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PriceChart: typeof import('./components/Cards/PriceChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sideboard: typeof import('./components/common/Sideboard.vue')['default']
    TopArticle: typeof import('./components/home/TopArticle.vue')['default']
  }
}
