name: CI

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1
          cache: 'yarn'
      - run: |
          yarn install
          yarn build-only
      - name: List files in dist directory
        run: ls -R dist
      - name: Clear directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Removing old files..."
            rm -rf /var/www/ygo_front/*
      - name: deploy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/**/*'
          target: '/var/www/ygo_front'
          strip_components: 1
