name: CI

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1
          cache: 'yarn'
      - run: yarn

      - name: Build
        run: yarn build-only

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/*'
          remote-path: '/usr/share/nginx/html'
